### PR TITLE
Darranl wfly 17651

### PR DESCRIPTION
**Pull request by jmesnil**
@darranl This rebases your archetype on top of `main` and updated the dependencies to read them from the parent pom.xml.

### CODE REVIEW

**Comment by darranl** [comment]
@jmesnil I will have a look at this but if we have multiple collaborators I would prefer to avoid rebases and just have a topic branch that moves forward.

**Comment by jmesnil** [comment]
@darranl It's worth rebasing at least once as the archetypes get their version from the parent pom now (since fc90c2eaccd858061018847ca7e2b1553dd7cc4b) otherwise I agree with you

**Comment by darranl** [comment]
@jmesnil It is the word "rebase" I am talking about, I completely agree with merging in the upstream changes so we are not diverged.

**Comment by darranl** [comment]
@jmesnil FYI I have synced with main here https://github.com/wildfly/wildfly-archetypes/pull/47 and applied the latest changes from your branch.  Except the last commit you just pushed.

**Pull request closed without merging**
